### PR TITLE
scrubmix reports

### PR DESCRIPTION
**Pull request by laurieskelly**
adding the analysis files and report generators I made today. 

the python script `scrub_mix_reports/scrub_mix_reports.py` creates `.png` plots and `html` reports, so I did not commit those to the group repo. they're blocked in the .gitignore as well. 

i had a great time at the event today. thank you

### CODE REVIEW

**Comment by DSLituiev** [comment]
great! 
can you please rename `lrs_goldengate_EDA.ipynb` as on the master or any meaningful name?

**Comment by DSLituiev** [comment]
do you actually need `scrub_mix_reports/reports/.keep` and  `scrub_mix_reports/reports/img/.keep` files?

**Comment by laurieskelly** [comment]
If someone runs the script it will put the html and png files in those directories. It does do a check for them and will create them if they don't exist, but the .keep files are just for making the directories exist in the repo filesystem. 

& I'll fix the notebook name now thank you

**Comment by laurieskelly** [comment]
arrrrrrrgh. Shoot, that did not help I don't think. Listen, I never really meant to include that notebook in the pull request anyway.

I have a local copy that will not be affected by the master branch changes. Please do whatever is easiest to resolve this.  I think this file is unimportant. I apologize for the inconvenience

**Comment by DSLituiev** [comment]
merged

**Pull request merged**
