### PR TITLE
Script for cleaning data and the cleaned file.

### PR DESCRIPTION
**Pull request by hougs**
Imputes information about species.

### CODE REVIEW

**Comment by evbettor** [comment]
other replaces for cleaning i found (manually):

df$species_lower[df$species_lower == 'anagalis arvensis'] <- 'anagallis arvensis'
df$species_lower[df$species_lower == 'gnaphalium luteo-album'] <- 'gnaphalium luteoalbum'
df$species_lower[df$species_lower == 'ceanothus thrysiflorus'] <- 'ceanothus thyrsiflorus'
df$species_lower[df$species_lower == 'anthriscus caucalis'] <- 'anthriscus cacaulis'
df$species_lower[df$species_lower == 'marah fabaceous'] <- 'marah fabaceus'

**Comment by RocioSNg** [comment]
in addition to "-" there are blanks ("") in the dataframe that can be replaced with NAs

**Comment by evbettor** [comment]
also fyi the file 'cleaned_landsend_veg_2007_2012.csv adds 76 additional observations, 

any idea what they are?

here they are the cleaned and original counted observations by year:

cleaned
2008 2009 2010 2011 2012 2013 2014 
505  518  816  859  964    5    1 

original
2008 2009 2010 2011 2012 2013 2014 
498  505  789  857  937    5    1

**Comment by hougs** [comment]
@evbettor I firgured out why-- some species have non unique asscioated fields in the dataframe:
ie:
elymus glaucus       ELGL        Native    Perennial   Grass
elymus glaucus       ELGL        Native    Perennial    Forb

going to clean those now too.

**Pull request merged**
